name: 部署到 GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 檢出代碼
        uses: actions/checkout@v3
        
      - name: 設置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
          
      - name: 安裝依賴
        run: |
          cd frontend
          npm ci
          
      - name: 構建項目
        run: |
          cd frontend
          npm run build
          
      - name: 配置 GitHub Pages
        uses: actions/configure-pages@v3
        
      - name: 上傳構建產物
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'frontend/build'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 